spring:
  profiles:
    active: staging
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
jwt:
  secret: saltandpepper

---
spring:
  profiles: staging
  data.mongodb:
    uri: mongodb+srv://admin:admin@firstcluster.nrj8x.mongodb.net/Twitter?retryWrites=true&w=majority
---
server:
  port: 8080

